name: Deployment
on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

# Build
# Publish the artefact?
# Deploy the artefact into gergling.github.io/achievements

# Steps 3 onward from this tutorial look promising: https://github.com/gitname/react-gh-pages
# Also, maybe all sketch shows should go in as bronze? Maybe new jobs as well.
# First stand-up show should go in? Subsequent stand-up shows?
# Moving house is kinda huge so those should probably go in as gold.
        
